name: control-commit-message
on:
  workflow_dispatch:
    inputs:
      message: 
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run a multi-line script
        shell: pwsh
        env:
          message: ${{ github.event.inputs.message }}
        run: |
          git config --global user.name ${{ github.actor }}         
          $message = $env:message
          Set-Content -Path  message.txt -Value $message
          git add --all
          git commit -am $message
          git push
