name: gh-run-list

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Run a multi-line script
        run: |
          gh run list --workflow control-commit-message --json databaseId,headBranch,status
