name: gh-run-list

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: gh run list
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # runner doesn't have 2.4.0 yet, so forcing
          choco upgrade gh
          gh --version 
          gh run list --workflow control-commit-message --json databaseId,headBranch,status
